"""Unit tests for the Sentinel model training pipeline."""

import numpy as np
import pandas as pd
import pytest


def test_isolation_forest_trains_and_predicts():
    """IsolationForest should fit and return valid predictions."""
    from sklearn.ensemble import IsolationForest
    from sklearn.preprocessing import StandardScaler

    X = np.random.default_rng(42).standard_normal((200, 4))
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    model = IsolationForest(n_estimators=10, contamination=0.05, random_state=42)
    model.fit(X_scaled)

    preds = model.predict(X_scaled)
    scores = model.score_samples(X_scaled)

    assert len(preds) == 200
    assert set(preds).issubset({-1, 1})
    assert len(scores) == 200
    assert scores.min() < scores.max()


def test_preprocess_adds_feature_columns():
    """Preprocessing should add rolling mean, std, and diff columns."""
    from src.data.ingest import preprocess

    df = pd.DataFrame(
        {
            "timestamp": pd.date_range("2024-01-01", periods=50, freq="5min"),
            "value": np.random.default_rng(0).uniform(70, 90, 50),
        }
    )
    result = preprocess(df)

    assert "value_rolling_mean" in result.columns
    assert "value_rolling_std" in result.columns
    assert "value_diff" in result.columns
    assert len(result) == 50
    assert result["timestamp"].is_monotonic_increasing


def test_preprocess_drops_nulls():
    """Preprocessing should handle and drop NaN rows."""
    from src.data.ingest import preprocess

    df = pd.DataFrame(
        {
            "timestamp": pd.date_range("2024-01-01", periods=10, freq="5min"),
            "value": [1.0, None, 3.0, None, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0],
        }
    )
    result = preprocess(df)
    assert result.isnull().sum().sum() == 0


def test_feature_columns_match_model_expectation():
    """Feature columns generated by ingest must match FEATURE_COLS in train."""
    from src.data.ingest import preprocess
    from src.models.train import FEATURE_COLS

    df = pd.DataFrame(
        {
            "timestamp": pd.date_range("2024-01-01", periods=30, freq="5min"),
            "value": np.random.default_rng(1).uniform(70, 90, 30),
        }
    )
    result = preprocess(df)
    for col in FEATURE_COLS:
        assert col in result.columns, f"Missing feature column: {col}"


def test_anomaly_contamination_rate():
    """Isolation Forest anomaly rate should be close to the contamination param."""
    from sklearn.ensemble import IsolationForest
    from sklearn.preprocessing import StandardScaler

    rng = np.random.default_rng(99)
    X = rng.standard_normal((500, 4))
    contamination = 0.05

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    model = IsolationForest(contamination=contamination, random_state=42)
    model.fit(X_scaled)
    preds = model.predict(X_scaled)

    actual_rate = (preds == -1).sum() / len(preds)
    # Should be close to contamination within ±2%
    assert abs(actual_rate - contamination) < 0.02
